---
volumes:
  hana_data:
    size: 100%FREE
    vg: vg_hana_data_{{ sap_sid }}
    mountpoint: /hana/data/{{ sap_sid }}
    pv: "{{ luns_data }}"
    lvopts: --stripes {{ luns_data|length}} --stripesize 128
    fsopts: -b size=4096 -d su=128k,sw={{ luns_data|length }}
  hana_log:
    size: 100%FREE
    vg: vg_hana_log_{{ sap_sid }}
    mountpoint: /hana/log/{{ sap_sid }}
    pv: "{{ luns_log }}"
    lvopts: --stripes {{ luns_log|length }} --stripesize 32
    fsopts: -b size=4096 -d su=32k,sw={{ luns_log|length }}
  hana_shared:
    size: 100%FREE
    vg: vg_hana_shared
    mountpoint: /hana/shared
    pv: "{{ luns_shared }}"