---

- name: create volume groups
  with_dict: "{{ volumes }}"
  lvg:
    vg: "{{ item.value.vg }}"
    pvs: "{{ item.value.pv }}"

- name: create logical volumes
  with_dict: "{{ volumes }}"
  lvol:
    vg: "{{ item.value.vg }}"
    lv: lv_{{ item.key }}
    size: "{{ item.value.size }}"
    opts: "{{ item.value.lvopts | default(omit) }}"

- name: create filesystems
  with_dict: "{{ volumes }}"
  filesystem:
    dev:  /dev/{{ item.value.vg }}/lv_{{ item.key }}
    fstype: "{{ item.value.fstype | default('xfs')}}"
    opts: "{{ item.value.fsopts | default(omit) }}"

- name: mount and make fstab entries
  with_dict: "{{ volumes }}"
  mount:
    name: "{{ item.value.mountpoint }}"
    fstype: "{{ item.value.fstype | default('xfs')}}"
    opts: defaults
    src: "/dev/{{ item.value.vg }}/lv_{{ item.key }}"
    state: mounted

...
