inst_patterns:
  - sap-hana

inst_packages:
  - gdisk
  - sg3_utils
  - lvm2
  - libopenssl1_0_0
  - libssh2-1
  - saptune

fqdnhost: "{% if public_ip %} {{ fqdn }} {% else %} {{ vm_name }}.{{ fqdn }} {% endif %}"
