---
# This role installs XSA on top of an existing HANA 2.0 instance
- name: Deploy hdblcm install template for XSA
  template:
    src: hdblcm_xsa.cfg.j2
    dest: /hana/shared/install/hdblcm_xsa.cfg

- name: Deploy hdblcm password file for XSA
  template:
    src: hdblcm_xsa.passwords.j2
    dest: /hana/shared/install/hdblcm_xsa.passwords

- name: Download XSA Runtime
  get_url:
    url: "{{ url_xsa_runtime }}"
    dest: /hana/shared/install/EXTAPPSER00P.SAR

- name: Download XSA Components
  with_items: "{{ list_xsa_files }}"
  get_url:
    url: "{{ url_prefix }}{{ item }}"
    dest: /hana/shared/install/

- name: Extract XSA Runtime
  command: ./SAPCAR_LINUX.EXE -manifest SIGNATURE.SMF -xvf EXTAPPSER00P.SAR -R EXTAPPSER00P
  args:
    chdir: /hana/shared/install
    creates: /hana/shared/install/EXTAPPSER00P

- name: Run hdblcm to install XSA components
  shell: "pwd=$(<hdblcm_xsa.passwords); rm hdblcm_xsa.passwords; echo $pwd | SAP_HANA_DATABASE/hdblcm --configfile=hdblcm_xsa.cfg --batch --read_password_from_stdin=xml"
  args:
    chdir: /hana/shared/install
