---
- hosts: all
  become: true
  roles:
    - disk-setup
    - hostprep
    - saphana-install
    - { role: xsa-install, when: install_xsa == true }
    - { role: cockpit-download, when: install_xsa == true and install_cockpit == true }

- hosts: all
  become: true
  become_user: "{{ sap_sid|lower }}adm"
  roles:
    - { role: cockpit-install, when: install_xsa == true and install_cockpit == true }
