- name: Add host to hosts file
  lineinfile:
    path: /etc/hosts
    insertafter: '^127.0.0.1'
    line: "{{ nic_ip }}    {{ fqdn }} {{ vm_name }}"

- name: Set proxy server
  template:
    src: "{{ proxy_src }}"
    dest: "{{ proxy_dest }}"
    owner: root
    group: root
    mode: "0644"

- name: Register OS
  shell: |
    SUSEConnect -e {{ reg_user }} -r {{ reg_code }} -u https://scc.suse.com
    SUSEConnect -p sle-module-legacy/15/x86_64

- name: Install patterns
  zypper:
    name="{{ inst_patterns }}"
    state=latest
    type=pattern

- name: Install packages
  zypper:
    name="{{ inst_packages }}"
    state=latest

- name: Configure saptune
  shell: |
    saptune daemon start
    saptune solution apply HANA
