- name: Add host to hosts file
  lineinfile:
    path: /etc/hosts
    insertafter: '^127.0.0.1'
    line: "{{ nic_ip }}    {{ fqdn }} {{ vm_name }}"

- name: Register SUSE Cloud SMT
  command: /usr/sbin/registercloudguest --force-new

- name: Install patterns
  zypper:
    name="{{ inst_patterns }}"
    state=latest
    type=pattern

- name: Install packages
  zypper:
    name="{{ inst_packages }}"
    state=latest

- name: Configure saptune
  shell: |
    saptune daemon start
    saptune solution apply HANA
